# Generated by Django 5.1.1 on 2026-01-13 19:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.UniqueConstraint(fields=('provider', 'date', 'start_time', 'end_time'), name='uniq_timeslot_provider_date_start_end'),
        ),
    ]
